<link rel="stylesheet" href="styles.css" type="text/css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

---

### *Selected Publications*

---

##### Published Conference Papers 

Zhang, Qiaoning, **Esterwood, Connor**, Yang, X. Jessie, & RobertJr, Lionel P. (2019). An Automated Vehicle (AV) like Me? The Impact of Personality Similarities and Differences between Humans and AVs. Association for the Advancement of Artificial Intelligence 2019 Symposium

Zhao, H., Azevedo-Sa, H., **Esterwood, C.**, Yang, X. J., Robert, L., & Tilbury, D. (2019). Error Type, Risk, Performance, and Trust: Investigating the Different Impacts of false alarms and misses on Trust and Performance. Ground Vehicle Systems Engineering and Technology Symposium. 2019.

---

#### *In The News*

---

###### *CNET*

- Turns out humans want self-driving cars to possess a personality
- <https://www.cnet.com/roadshow/news/self-driving-cars-human-personality/>*


###### *The Media Hq*

- What individuals want in an automated car
- <https://themediahq.com/what-individuals-want-in-an-automated-car/>*


###### *Scienceblog*

- What Humans Want In An Automated Car
- <https://scienceblog.com/511942/what-humans-want-in-an-automated-car/>*


###### *Techcentury*

- UM study finds what people want in an autonomous car
- <https://www.techcentury.com/2019/11/08/um-study-finds-what-people-want-in-an-autonomous-car/>


###### *Techxplore*

- What humans want in an automated car
- <https://techxplore.com/news/2019-11-humans-automated-car.html>


###### *Small Tech News*

- New research suggests people may want self-driving cars to show personality
- <https://www.smalltechnews.com/archives/9017>



###### *Mirage News*

- What humans want in an automated car
- <https://www.miragenews.com/what-humans-want-in-an-automated-car/>


###### *Abudhabi News*

- Turns out humans want self-driving cars to possess a personality
- <https://abudhabi-news.com/English/6847312/Turns-out-humans-want-self-driving-cars-to-possess-a-personality---Roadshow>


###### *Pressfrom.info <http://ressfrom.info>*

- Turns out humans want self-driving cars to possess a personality
- <https://pressfrom.info/ca/autos/news/-179816-turns-out-humans-want-self-driving-cars-to-possess-a-personality.html>


---

*This Site is Made With Love in R*
